package postgres

import (
	"context"
	"encoding/json"
	"fmt"

	"metapus/internal/core/id"
	"metapus/internal/domain/automations"
)

// AutomationFileRepo implements automations.FileRepository using the tenant database.
type AutomationFileRepo struct{}

// NewAutomationFileRepo creates a new file repository.
func NewAutomationFileRepo() *AutomationFileRepo {
	return &AutomationFileRepo{}
}

// Save inserts a new automation file. The ID is generated by the database.
func (r *AutomationFileRepo) Save(ctx context.Context, file *automations.AutomationFile) error {
	txm := MustGetTxManager(ctx)
	q := txm.GetQuerier(ctx)

	metaJSON, err := json.Marshal(file.Metadata)
	if err != nil {
		return fmt.Errorf("marshal file metadata: %w", err)
	}

	query := `
		INSERT INTO sys_automation_files (rule_id, file_name, mime_type, file_data, file_size, row_count, metadata, expires_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		RETURNING id, created_at`

	err = q.QueryRow(ctx, query,
		file.RuleID, file.FileName, file.MimeType, file.FileData,
		file.FileSize, file.RowCount, metaJSON, file.ExpiresAt,
	).Scan(&file.ID, &file.CreatedAt)
	if err != nil {
		return fmt.Errorf("insert automation file: %w", err)
	}

	return nil
}

// GetByID retrieves a file by ID, including binary data.
func (r *AutomationFileRepo) GetByID(ctx context.Context, fileID id.ID) (*automations.AutomationFile, error) {
	txm := MustGetTxManager(ctx)
	q := txm.GetQuerier(ctx)

	query := `
		SELECT id, rule_id, file_name, mime_type, file_data, file_size, row_count, metadata, expires_at, created_at
		FROM sys_automation_files
		WHERE id = $1`

	var file automations.AutomationFile
	var metaJSON []byte

	err := q.QueryRow(ctx, query, fileID).Scan(
		&file.ID, &file.RuleID, &file.FileName, &file.MimeType,
		&file.FileData, &file.FileSize, &file.RowCount, &metaJSON,
		&file.ExpiresAt, &file.CreatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("query automation file %s: %w", fileID, err)
	}

	if metaJSON != nil {
		if err := json.Unmarshal(metaJSON, &file.Metadata); err != nil {
			return nil, fmt.Errorf("unmarshal file metadata: %w", err)
		}
	}

	return &file, nil
}

// DeleteExpired removes all files past their expiration time.
func (r *AutomationFileRepo) DeleteExpired(ctx context.Context) (int, error) {
	txm := MustGetTxManager(ctx)
	q := txm.GetQuerier(ctx)

	tag, err := q.Exec(ctx, `DELETE FROM sys_automation_files WHERE expires_at < NOW()`)
	if err != nil {
		return 0, fmt.Errorf("delete expired automation files: %w", err)
	}

	return int(tag.RowsAffected()), nil
}

// Ensure interface compliance.
var _ automations.FileRepository = (*AutomationFileRepo)(nil)
