package platform

import (
	"metapus/internal/domain/posting"
)

// Re-export posting extension interfaces for client extensions.
// Extensions use these to add custom register types without importing
// internal packages directly.

// RegisterVisitor examines a Postable document and collects register-specific movements.
type RegisterVisitor = posting.RegisterVisitor

// RegisterRecorder handles recording and reversal of movements for one register type.
type RegisterRecorder = posting.RegisterRecorder

// PostingValidator is an optional interface for recorders that validate before recording.
type PostingValidator = posting.PostingValidator

// Postable is implemented by documents that can generate register movements.
type Postable = posting.Postable

// MovementSet contains all register movements generated by a document.
type MovementSet = posting.MovementSet

// PostHook is called during posting lifecycle.
type PostHook = posting.PostHook
