// Package posting provides the document posting engine.
// Posting is the process of recording document movements to accumulation registers.
package posting

import (
	"context"
	"fmt"

	"metapus/internal/core/apperror"
	"metapus/internal/core/entity"
	"metapus/internal/core/id"
	"metapus/internal/core/tenant"
	"metapus/pkg/logger"
)

// DocumentLocker acquires an exclusive transactional lock on a document.
// Prevents concurrent posting/unposting of the same document (double-click, parallel tabs).
// Must be called inside a transaction — the lock is released on COMMIT/ROLLBACK.
type DocumentLocker interface {
	LockDocument(ctx context.Context, docType string, docID id.ID) error
}

// Postable is implemented by documents that can generate register movements.
type Postable interface {
	// GetID returns the document ID
	GetID() id.ID

	// GetDocumentType returns the document type name (e.g., "GoodsReceipt")
	GetDocumentType() string

	// GetPostedVersion returns the current posting version
	GetPostedVersion() int

	// IsPosted returns true if document is currently posted
	IsPosted() bool

	// CanPost validates if document can be posted
	CanPost(ctx context.Context) error

	// MarkPosted updates the document's posted state
	MarkPosted()

	// MarkUnposted clears the posted state
	MarkUnposted()
}

// MovementSet contains all register movements generated by a document.
type MovementSet struct {
	StockMovements      []entity.StockMovement
	CostMovements       []entity.CostMovement
	SettlementMovements []entity.SettlementMovement

	// Extensions holds movements for custom register types added by client extensions.
	// Key: register name (e.g., "production"), Value: typed movement slice.
	// Custom RegisterVisitor implementations write here; custom RegisterRecorder reads.
	Extensions map[string]any
}

// LineCounter is an optional interface for Postable documents
// that can report their line count for pre-allocation hints.
type LineCounter interface {
	GetLineCount() int
}

// NewMovementSet creates an empty movement set.
func NewMovementSet() *MovementSet {
	return &MovementSet{}
}

// NewMovementSetWithCapacity creates a movement set with pre-allocated slices.
// Reduces allocations for documents with many lines (avoids repeated growslice).
func NewMovementSetWithCapacity(lineCount int) *MovementSet {
	if lineCount <= 0 {
		return &MovementSet{}
	}
	return &MovementSet{
		StockMovements:      make([]entity.StockMovement, 0, lineCount),
		CostMovements:       make([]entity.CostMovement, 0, lineCount),
		SettlementMovements: make([]entity.SettlementMovement, 0, lineCount),
	}
}

// AddStock adds a stock movement.
func (m *MovementSet) AddStock(movement entity.StockMovement) {
	m.StockMovements = append(m.StockMovements, movement)
}

// AddCost adds a cost movement.
func (m *MovementSet) AddCost(movement entity.CostMovement) {
	m.CostMovements = append(m.CostMovements, movement)
}

// AddSettlement adds a settlement movement.
func (m *MovementSet) AddSettlement(movement entity.SettlementMovement) {
	m.SettlementMovements = append(m.SettlementMovements, movement)
}

// SetExtension stores custom register movements in the extension map.
func (m *MovementSet) SetExtension(name string, data any) {
	if m.Extensions == nil {
		m.Extensions = make(map[string]any)
	}
	m.Extensions[name] = data
}

// GetExtension retrieves custom register movements by name.
func (m *MovementSet) GetExtension(name string) (any, bool) {
	if m.Extensions == nil {
		return nil, false
	}
	v, ok := m.Extensions[name]
	return v, ok
}

// IsEmpty returns true if no movements were generated.
func (m *MovementSet) IsEmpty() bool {
	return len(m.StockMovements) == 0 &&
		len(m.CostMovements) == 0 &&
		len(m.SettlementMovements) == 0 &&
		len(m.Extensions) == 0
}

// TotalCount returns total number of movements.
func (m *MovementSet) TotalCount() int {
	return len(m.StockMovements) + len(m.CostMovements) + len(m.SettlementMovements)
}

// Engine orchestrates document posting operations.
// It coordinates validation, movement generation, and register updates.
// Movement generation is delegated to RegisterVisitor instances (Visitor pattern).
// Movement recording/reversal is delegated to RegisterRecorder instances.
// In Database-per-Tenant architecture, TxManager is obtained from context.
type Engine struct {
	recorders []RegisterRecorder
	docLocker DocumentLocker // optional; nil = no advisory lock
	visitors  []RegisterVisitor

	// Hooks for extensibility
	beforePost []PostHook
	afterPost  []PostHook
}

// PostHook is called during the posting lifecycle.
//
// IMPORTANT: Transaction semantics:
//   - beforePost hooks run OUTSIDE the posting transaction (before RunInTransaction).
//     They are suitable for validation and fail-fast checks, but MUST NOT modify
//     database state — such changes won't be rolled back on posting failure.
//   - afterPost hooks also run OUTSIDE the transaction, after successful commit.
//     Use them for side-effects (notifications, cache invalidation, audit logs).
//
// For logic that MUST run within the posting transaction, use RegisterRecorder
// (RecordFromSet/ReverseForDocument are called inside the transaction).
type PostHook func(ctx context.Context, doc Postable) error

// NewEngine creates a new posting engine.
// In Database-per-Tenant, TxManager is obtained from context.
// docLocker is optional — pass nil to skip advisory locking (e.g. in tests).
// recorders define which registers the engine writes to (use DefaultRecorders for built-in).
//
// Example:
//
//	recorders := posting.DefaultRecorders(stockSvc, costSvc, settlementSvc)
//	engine := posting.NewEngine(docLocker, recorders...)
func NewEngine(docLocker DocumentLocker, recorders ...RegisterRecorder) *Engine {
	e := &Engine{
		recorders: recorders,
		docLocker: docLocker,
	}
	// Register built-in visitors
	e.visitors = append(e.visitors, &StockVisitor{}, &CostVisitor{}, &SettlementVisitor{})
	return e
}

// AddVisitor registers an additional register visitor.
// Use this to extend the engine with new register types.
func (e *Engine) AddVisitor(v RegisterVisitor) {
	e.visitors = append(e.visitors, v)
}

// AddRecorder registers an additional register recorder.
// Use this to extend the engine with new register types for recording/reversal.
func (e *Engine) AddRecorder(r RegisterRecorder) {
	e.recorders = append(e.recorders, r)
}

// OnBeforePost registers a hook to run BEFORE the posting transaction.
// Suitable for: validation, permission checks, fail-fast logic.
// NOT suitable for: database writes (won't be in the same transaction).
func (e *Engine) OnBeforePost(hook PostHook) {
	e.beforePost = append(e.beforePost, hook)
}

// OnAfterPost registers a hook to run AFTER successful posting commit.
// Suitable for: notifications, cache invalidation, audit logging.
// NOT suitable for: database writes that must be atomic with posting.
func (e *Engine) OnAfterPost(hook PostHook) {
	e.afterPost = append(e.afterPost, hook)
}

// Post records document movements to registers.
// This is the main posting operation - it:
// 1. Validates the document can be posted
// 2. Generates movements from document data
// 3. Checks stock availability (for expense movements)
// 4. Records movements to registers
// 5. Updates document posted state
//
// If the document is already posted, it will be re-posted (like 1C behavior).
func (e *Engine) Post(ctx context.Context, doc Postable, updateDoc func(context.Context) error) error {
	return e.doPost(ctx, doc, updateDoc)
}

// doPost is the unified posting implementation.
// Handles both first-time posting and re-posting.
// If the document is already posted, old movements are reversed before recording new ones.
func (e *Engine) doPost(ctx context.Context, doc Postable, updateDoc func(context.Context) error) error {
	isRepost := doc.IsPosted()

	// Validate document can be posted
	if err := doc.CanPost(ctx); err != nil {
		return fmt.Errorf("cannot post: %w", err)
	}

	// Run before-post hooks
	for _, hook := range e.beforePost {
		if err := hook(ctx, doc); err != nil {
			return fmt.Errorf("before-post hook: %w", err)
		}
	}

	// Execute posting in transaction
	txm, err := tenant.GetTxManager(ctx)
	if err != nil {
		return apperror.NewInternal(err).WithDetail("missing", "tx_manager")
	}
	err = txm.RunInTransaction(ctx, func(ctx context.Context) error {
		// Advisory lock: prevent concurrent posting of the same document
		if e.docLocker != nil {
			if err := e.docLocker.LockDocument(ctx, doc.GetDocumentType(), doc.GetID()); err != nil {
				return fmt.Errorf("lock document: %w", err)
			}
		}

		// If re-posting, reverse old movements first
		if isRepost {
			oldVersion := doc.GetPostedVersion()
			if err := e.reverseAllMovements(ctx, doc.GetID(), oldVersion+1); err != nil {
				return fmt.Errorf("reverse old movements: %w", err)
			}
		}

		// Collect movements via registered visitors (Visitor pattern)
		movements, err := e.collectMovements(ctx, doc)
		if err != nil {
			return fmt.Errorf("collect movements: %w", err)
		}

		if movements.IsEmpty() {
			logger.Warn(ctx, "document generated no movements",
				"document_id", doc.GetID(),
				"document_type", doc.GetDocumentType())
		}

		// Run pre-post validators (e.g., stock availability check)
		for _, rec := range e.recorders {
			if validator, ok := rec.(PostingValidator); ok {
				if err := validator.ValidateBeforePost(ctx, movements); err != nil {
					return err
				}
			}
		}

		// Record movements to registers via recorders
		for _, rec := range e.recorders {
			if err := rec.RecordFromSet(ctx, movements); err != nil {
				return fmt.Errorf("record %s movements: %w", rec.Name(), err)
			}
		}

		// Update document posted state
		doc.MarkPosted()
		if err := updateDoc(ctx); err != nil {
			return fmt.Errorf("update document: %w", err)
		}

		return nil
	})

	if err != nil {
		return err
	}

	// Run after-post hooks (outside transaction)
	for _, hook := range e.afterPost {
		if hookErr := hook(ctx, doc); hookErr != nil {
			logger.Error(ctx, "after-post hook failed",
				"document_id", doc.GetID(),
				"error", hookErr)
		}
	}

	action := "posted"
	if isRepost {
		action = "reposted"
	}
	logger.Info(ctx, "document "+action,
		"document_id", doc.GetID(),
		"document_type", doc.GetDocumentType(),
		"version", doc.GetPostedVersion())

	return nil
}

// Unpost reverses document movements from registers.
func (e *Engine) Unpost(ctx context.Context, doc Postable, updateDoc func(context.Context) error) error {
	if !doc.IsPosted() {
		// Idempotent no-op: document is already unposted — nothing to do.
		// Analogous to 1C behavior: "Отменить проведение" on an unposted document is a silent success.
		logger.Debug(ctx, "unpost skipped: document already unposted",
			"document_id", doc.GetID(),
			"document_type", doc.GetDocumentType())
		return nil
	}

	txm, err := tenant.GetTxManager(ctx)
	if err != nil {
		return apperror.NewInternal(err).WithDetail("missing", "tx_manager")
	}
	err = txm.RunInTransaction(ctx, func(ctx context.Context) error {
		// Advisory lock: prevent concurrent unposting of the same document
		if e.docLocker != nil {
			if err := e.docLocker.LockDocument(ctx, doc.GetDocumentType(), doc.GetID()); err != nil {
				return fmt.Errorf("lock document: %w", err)
			}
		}

		// Delete movements for this document version across all registers
		if err := e.reverseAllMovements(ctx, doc.GetID(), doc.GetPostedVersion()+1); err != nil {
			return fmt.Errorf("reverse movements: %w", err)
		}

		// Update document state
		doc.MarkUnposted()
		if err := updateDoc(ctx); err != nil {
			return fmt.Errorf("update document: %w", err)
		}

		return nil
	})

	if err != nil {
		return err
	}

	logger.Info(ctx, "document unposted",
		"document_id", doc.GetID(),
		"document_type", doc.GetDocumentType())

	return nil
}

// collectMovements iterates all registered visitors to collect register movements.
// Uses LineCounter interface for pre-allocation when available.
func (e *Engine) collectMovements(ctx context.Context, doc Postable) (*MovementSet, error) {
	var set *MovementSet
	if lc, ok := doc.(LineCounter); ok {
		set = NewMovementSetWithCapacity(lc.GetLineCount())
	} else {
		set = NewMovementSet()
	}
	for _, v := range e.visitors {
		if err := v.CollectMovements(ctx, doc, set); err != nil {
			return nil, fmt.Errorf("visitor %s: %w", v.Name(), err)
		}
	}
	return set, nil
}

// reverseAllMovements deletes movements across all register recorders for a document version.
func (e *Engine) reverseAllMovements(ctx context.Context, recorderID id.ID, beforeVersion int) error {
	for _, rec := range e.recorders {
		if err := rec.ReverseMovements(ctx, recorderID, beforeVersion); err != nil {
			return fmt.Errorf("reverse %s: %w", rec.Name(), err)
		}
	}
	return nil
}
