package automations

import (
	"context"
	"time"

	"metapus/internal/core/id"
)

// AutomationFile represents a generated report file stored temporarily
// in sys_automation_files. Cleaned up by the worker after ExpiresAt.
type AutomationFile struct {
	ID        id.ID          `json:"id"`
	RuleID    id.ID          `json:"ruleId"`
	FileName  string         `json:"fileName"`
	MimeType  string         `json:"mimeType"`
	FileData  []byte         `json:"-"` // Excluded from JSON to prevent accidental serialization
	FileSize  int            `json:"fileSize"`
	RowCount  int            `json:"rowCount"`
	Metadata  map[string]any `json:"metadata"`
	ExpiresAt time.Time      `json:"expiresAt"`
	CreatedAt time.Time      `json:"createdAt"`
}

// FileRepository persists and retrieves generated report files.
type FileRepository interface {
	// Save stores a new file. ID is generated by the database.
	Save(ctx context.Context, file *AutomationFile) error
	// GetByID retrieves a file by ID, including binary data.
	GetByID(ctx context.Context, fileID id.ID) (*AutomationFile, error)
	// DeleteExpired removes all files past their expiration time.
	// Returns the number of deleted rows.
	DeleteExpired(ctx context.Context) (int, error)
}
